export const INCREASE_QTY = "INCREASE_QTY";
export const DECREASE_QTY = "DECREASE_QTY";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const UPDATE_PRICE = "UPDATE_PRICE";
export const PROCESSED_ITEM = "PROCESSED_ITEM";
